### ISSUE TITLE
Documentation about 

### ISSUE THREAD

**Issue by anhldbk** [apollographql/subscriptions-transport-ws#148]
In the document section about [Server](https://github.com/apollographql/subscriptions-transport-ws#server), it states that:

> Now, use your PubSub instance, along with your GraphQL schema, execute and subscribe

But I can't find any reference to the instance in the demo code:

```js
import { createServer } from 'http';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';
import { schema } from './my-schema';

const WS_PORT = 5000;

// Create WebSocket listener server
const websocketServer = createServer((request, response) => {
  response.writeHead(404);
  response.end();
});

// Bind it to port and start listening
websocketServer.listen(WS_PORT, () => console.log(
  `Websocket Server is now running on http://localhost:${WS_PORT}`
));

const subscriptionServer = SubscriptionServer.create(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server: websocketServer,
    path: '/graphql',
  },
);
```

There should be a PR addressing this issue, right?

**Comment by jthegedus** [comment]
I believe that was deprecated along with [SubscriptionManager](https://github.com/apollographql/subscriptions-transport-ws/blob/4d2ceb9b0bdf631d248a9ad2654a8c4e26946e51/README.md#L327), I could be mistaken as I'm only loosely following these changes. But it appears it shouldn't be there.

**Comment by dnalborczyk** [comment]
same here: http://dev.apollodata.com/tools/graphql-subscriptions/express.html, reference to _pubsub_ is missing. It's also not quite clear for the SubscriptionServer if the _constructor_, the (new) _create_ function, or either should be used.

**Comment by dotansimha** [comment]
@dnalborczyk Please note my PR: https://github.com/apollographql/subscriptions-transport-ws/pull/151

**Comment by dnalborczyk** [comment]
hey @dotansimha thanks for more clarification. though the main confusing point is still the missing reference to the PubSub instance.

let me clarify: prior to the latest changes one had to use the SubscriptionManager (now deprecated) like so (abbreviated):

from the former docs:
https://github.com/apollographql/graphql-subscriptions/blob/5eaee92cd50060b3f3637f00c53960f51a07d0b2/README.md

```
const pubsub = new PubSub();
const subscriptionManager = new SubscriptionManager({ pubsub });
```

from the latest docs:  https://github.com/apollographql/subscriptions-transport-ws#server

```
import { PubSub } from 'graphql-subscriptions';
export const pubsub = new PubSub();
```

what it comes down to: what do you do with (the exported) _pubsub_? or is it just a left-over from the old docs?

**Comment by dotansimha** [comment]
@dnalborczyk @anhldbk 
The next step of the README refers to `graphql-subscriptions` package, because this package is in charge of managing the actual PubSub and subscriptions. 

Basically, you need to create PubSub instance, and then use it to publish (`pubsub.publish('eventName', { ... })`), and you need to use the same PubSub instance to create your `AsyncIterator` instance, and connect it to your GraphQL schema definition.

You can see an example here: https://github.com/apollographql/graphql-subscriptions#getting-started-with-your-first-subscritpion  

`SubscriptionsManager` is deprecated, and no longer in use, and it will be removed in the next version of `graphql-subscriptions`. In the current implementation, you no longer need to connect your PubSub instance with the subscriptions handler, because you can just connect your PubSub events directly to the GraphQL schema.
