### ISSUE TITLE
Give reasons for hybrid transport

### ISSUE THREAD

**Issue by lorensr** [apollographql/subscriptions-transport-ws#322]
The README says it's an option—would be useful to also read why you might want to do it.

> When using this package for client side, you can choose either use HTTP request for Queries and Mutation and use the WebSocket for subscriptions only, or create a full transport that handles all type of GraphQL operations over the socket.

**Comment by jonaskello** [comment]
I guess one reason would be that HTTP can transport in parallel which ws cannot?

**Comment by nuragic** [comment]
If you need to send files you would need hybrid transport (until [this issue](https://github.com/jaydenseric/apollo-upload-client/issues/176) will be resolved 🤞). 😄

**Comment by nuragic** [comment]
If you need to integrate "monitoring" in your app (client) then HTTP requests instrumentation is much easier to add, in fact most of the monitoring tools (e.g. Elastic APM) automatically instrument HTTP requests for you (that's not the case with WS, it's not so easy to do even manually).

**Comment by nuragic** [comment]
If your app has first class realtime features then the full WS transport is the best choice IMO. With HTTP, headers (e.g auth tokens, cookies, etc) are sent in each request, plus latency of each request... With WS, once you connect, there's no more overhead: just realtime communication between client and server. 💘

**Comment by nuragic** [comment]
To clarify this point: 

> If you need to integrate "monitoring" in your app [...]

You can have both full WS transport _and_ monitoring: the thing is that if you need to monitor "end to end" (e.g. operations triggered from your app UI way down to the DB) you would need to start a custom transaction from the [WS client](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts). 

Another approach is to start monitoring from the [WS server](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts): this is easier to implement because you have the `onOperation` and `onOperationComplete` callbacks on where you can add your custom transaction logic (start/end/error).
