### ISSUE TITLE
Make sure this package exports something to add subscriptions to Apollo Client

### ISSUE THREAD

**Issue by stubailo** [apollographql/subscriptions-transport-ws#38]
https://medium.com/apollo-stack/graphql-subscriptions-in-apollo-client-9a2457f015fb#.37xz9hr75

Reported by @mlp5ab from scaphold

**Comment by drFabio** [comment]
Following the blog now and was searching the code because this part was not working. So the medium post said that there was an exported function that does not exist or the function goes by a different name now? Searched the code for [addGraphQLSubscriptions](https://github.com/apollostack/subscriptions-transport-ws/search?utf8=%E2%9C%93&q=addGraphQLSubscriptions)  and it reported nothing does this function exist somewhere or the post was an spec ?

**Comment by anhldbk** [comment]
@helfer Open for a PR against this issue?

**Comment by helfer** [comment]
@anhldbk yes, definitely!

**Comment by Urigo** [comment]
Implemented in this PR: https://github.com/apollographql/subscriptions-transport-ws/pull/64 (thanks @Darkbladecr), and we will soon release it in a new version.
