### ISSUE TITLE
Operation handler should be called in case of `connection_error`

### ISSUE THREAD

**Issue by karthikvt26** [apollographql/subscriptions-transport-ws#474]
Current implementation calls a function if configured in case of `connection_error` type returned by server.

Expected: 
Operation's handler needs to be called instead.

Kindly let me know if I am missing something? 

Edit: 

Source: https://github.com/apollographql/subscriptions-transport-ws/blob/dbcf2d8e1400158e62de2ff3ae97dd98916cd4bc/src/client.ts#L604

**Comment by wawhal** [comment]
Operation handler can't be called because the id of the operation is not known in case of `connection_error`.

It is somewhat of a problem. In case of `connection_error` they are simply calling the `connectionCallback` with the error payload without handling the error. The error is handled only in case of `gql_error`. This is a problem whenever somebody is exploring the subscriptions in GraphiQL because GraphiQL does not receive the payload sent in `connection_error`.

Seems like this library has an opinionated way of handling connection errors. 

The workflow they expect seem to be:

1. Client sends `connection_init` and `gql_start` together.
2. The server sends `connection_error` and `gql_error` in response to `connection_init` and `gql_start` respectively with the same payload and `gql_error` containing the `id`.

In this way, the handler can be called and the `connectionCallback` can also be called.

Somebody please correct me if I am wrong.
