### ISSUE TITLE
HTTP headers

### ISSUE THREAD

**Issue by atoy40** [apollographql/subscriptions-transport-ws#50]
It can be useful to be able to set headers in the client (W3CWebSocket class allows it via constructor fourth parameter), for example to include authentication informations

Anthony.

**Comment by Urigo** [comment]
see discussion here - https://github.com/apollostack/graphql-subscriptions/pull/27

**Comment by Urigo** [comment]
@atoy40 , the implementation of `W3CWebSocket` is for NodeJS environment only, and when using the native `WebSocket` of the browser, you can't add your own custom HTTP headers (it's browser's policy, that's why you can still do it when using NodeJS). 
However, we recently merged this PR: https://github.com/apollographql/subscriptions-transport-ws/issues/53 , which allows you to create a custom INIT message with custom data, so you can use it as headers object.
