### ISSUE TITLE
Guaranteed message delivery

### ISSUE THREAD

**Issue by casperstr** [apollographql/subscriptions-transport-ws#553]
As i understand it, the websocket protocol does not have any message delivery guarantees. What do you think about adding ACK's on all the messages so that the sender can resend the messages that didn't get delivered?

**Comment by sneko** [comment]
I'm also interested by ACK 😀 

@mistic do you have any plan on this? Or should we develop our own acknowledger over the same websocket? If so, do you have any advice to provide?

I need it to the second solution of my question here (that's hard to find a well-approved pattern): https://stackoverflow.com/questions/56808099/subscriptions-how-to-be-consistent-when-the-app-is-in-background

Thank you,

**Comment by scf4** [comment]
Would love to see this, too. Did you manage to develop a solution @sneko ?

**Comment by mistic** [comment]
@casperstr @sneko @scf4 it has been a long time since I found myself writing down that protocol 😃 If I remember correctly, our intention at that time was to design a pretty simple and effective protocol. In my usages of it in the past, I remember that I have implemented a top add on piece of software in rxjs to compliment the the subscriptions-transport-ws which I called connection-manager that was the responsible for dealing with the reconnect logic and resend the not delivered messages. I can share in case I'm able to find it 😃

**Comment by A-Tokyo** [comment]
@mistic sounds awesome!!

**Comment by mistic** [comment]
@A-Tokyo alright, I'll try to find it. I still might have it somewhere

**Comment by A-Tokyo** [comment]
Thanks 🚀

**Comment by sparcs360** [comment]
I'd be interested to see your `connection-manager` too @mistic - I'm guessing you've not had any luck finding it?
Maybe you can share your high-level method of solution instead?

**Comment by mistic** [comment]
I've searched across my NAS with no luck. It is probably stored in a disk I have installed in an old and damaged server. I'll install the disk into my NAS and I'll update here!

**Comment by A-Tokyo** [comment]
@mistic Thanks a lot for your commitment! The community will appreciate this! (:
