### ISSUE TITLE
Event loop blocked by too many executions

### ISSUE THREAD

**Issue by Shahor** [apollographql/subscriptions-transport-ws#626]
Hello 👋 

I have noticed something weird I would like to discuss with you for I'm not certain of its origin and am not comfortable enough with asyncIterators to diagnose this properly.

Using this [reproduction repo](https://github.com/Shahor/subscriptions-example) you can:
- set up a server accepting websocket connections
- set up 300 websocket connections
- publish 500 messages into redis to be computed

Doing this, you should obtain the [following behavior](https://imgur.com/k5JIQU2)

I am a bit confused as to why the event loop would be blocked. Is there an operation that should be async that isn't?

You can see this happen as well if the `filterFn` in `server/index.js:49` returns false so that nobody is interested in spinning the graphql execution for this message. (You might have to send more messages to witness it, `node publisher/index.js 1000`)

While I realize this makes for a lot of messages to be handled by the process
> Each message triggers 300 potential executions, this makes for 150 000 graphql executions to be performed
I would expect the whole process to be slow, but not for the event loop to be totally blocked.

This is especially true when we return `false` in the `filterFn` function (which means the issue doesn't come from the graphql layer)

(This issue was also filed here: https://github.com/davidyaha/graphql-redis-subscriptions/issues/173)

**Comment by gklijs** [comment]
Subscriptions are hard to scale. Even on the JVM most servers start breaking around 300 connections. Not sure this can be solved in a nice way. Some websocket implementations support broadcast, but it's hard to combine with the GraphQL 'way' of only getting what you want. Which seems that is you want to send the same events to many clients, in a scalable way, GraphQL might not be a good fit.

**Comment by Shahor** [comment]
There are a few things we can do though.

In the end, I split up the execution and transport part of my subscriptions to allow me to share Dataloaders for a graphql execution, and ran this for all my interested users. 

I then send that message through a pubsub subscription to all the websockets that are interested in it.

This allows me to control the exact throughput and scale my workers up when necessary. 
The transport layer just deals with writting in the websockets and therefore gets very scalable as well.

Don't know if this makes sense, I should probably write a longer post on the idea 🤔

**Comment by gklijs** [comment]
It does make sense. I'm currently busy with the Micronaut implementation. That's relevant cause they have a broadcast with an optional filter. In this case you could have something like prepared queries, and keep on the server just which client activated which subscription. When the server reads from pubsub, it could directly send it to all subscribers.
Instead of having to start some process for each subscription we only need to set a property, making it a lot lighter. The best thing about this approach would be clients can stay the same.

**Comment by gklijs** [comment]
The more I think about the more I think this would be a great way to make them scalable. I might even make a poc in the next weeks for the server to have it in a generic way.

Basically what you need is some way to describe in the schema, that for a certain subscription, instead of doing it the usual way, it should use a `data-source` and optionally a `data-filter` to send the subscription to the client instead of actually subscribing.

These `data-filter` objects are much lighter and can be used to broadcast the data from the `data-source`. Instead of canceling the subscription, when `stop` is called from the client, we only need to remove the filter.

This could be done even without changing the spec, by allowing some `subscription -> [source, filter]` mapping to a server.

**Comment by Shahor** [comment]
I'm a bit confused. 
Do you have an example of how that would work maybe?

**Comment by gklijs** [comment]
No, It's only in my head for now. And I don't know how websockets are implemented in node. But with micronaut you have a broadcast function that takes a message, and a predicate function. It will go trough all active session, and depending on the supplied function send the message.

So say you map `{ subscription { chatstream { message time }}}` to `id_1` and keep track of the id's subscribed to that subscription, you can use the broadcast function to send the message only to the subscribed connected clients.

**Comment by Shahor** [comment]
Oh yes, I see.

But this doesn't solve the execution layer which is imho the biggest issue here. 
Because of how it is designed right now, the subscription will be executed `n` times (which is expected, since each execution might yield different results) but without any way to share data{sources,loaders} between the executions. 

Therefore those calls get greedy and might choke your dbs real quick (psql for instance doesn't allow infinite connections and this becomes a problem fast)

**Comment by gklijs** [comment]
Yes, but you can bypass them in the server. But that does require the server to know how to resolve the subscription or reuse the existing one.

[from here it's just what came up in my mind, it might be usefull]

Theoretically you would only need to mark a subscription as 'doen't use context' and when the second client subscribes with the same query it gets the same messages as the first client. For this to work you would need to check for each query if it already exists, before running the execution of the query.

In my demo application you can also subscribe to transactions with a filter. In that case it would be nice if the server itself would read all the transactions, and uses the filter to pass some transactions to the client. This becomes more complex, but could be made to work. What's even better is that for micronaut all the session are maps. So onConnect you could put a `transaction -> false` function in the context and on subscription update it to something like `transaction -> transaction.amount > 100`. There are some edge cases trough, like if you want transaction using two different filters. Which make me thing about abusing the operationId. Just changing the behaviour when start/stop is called with certain operationId's.
