### ISSUE TITLE
Server-side catch of network loss to client

### ISSUE THREAD

**Issue by chelliwell** [apollographql/subscriptions-transport-ws#654]
I've looked through the open/closed issues here, but most similar seem to focus on the client behaviour. I'm using subscriptions with an Apollo Express server, and would like the server to catch when a client is no longer connected (e.g. network link fails). I've set a keepAlive value on the server (and I see the PingPong), but there doesn't seem to be any onDisconnect occurring when the client stops responding.
_Should_ I be able to get the server code to spot this?

**Comment by chelliwell** [comment]
I was just pausing my client app (in IDE) - it seems that Windows keeps the TCP link going, even though the websocket ping-pong is no longer going on. Doing a real hard disconnect of LAN cable, the server _does_ see the loss of connection.
It would be nice though if the transport triggered an event on the loss of ping-pong - e.g. what if the client app [but not TCPIP stack] has hung?

**Comment by javierfernandes** [comment]
I'm having the same problem here.
I have a backend API using "subscriptions-transport-ws" over a `node-http` server (createServer) like this

```js
  const server = http.createServer(defaultHandler)
  
this.subscriptionServer = new SubscriptionServer({
      schema: mySchema,
      onDisconnect: (webSocket, context) => {
        console.log('>>>> DISCONNECTED WS')
      },
      execute,
      subscribe,
    }, {
      server: server,
      path: '/subscriptions',
    })
  },
```

What I do to reproduce it is to launch the backend on my laptop and then use an ipad webapp that connects to the client. Then I turn wif "off" in the ipad and the `onDisconnect` callback never gets called :( 

Any clue on why this is happening or a lead to research ? I've seen that the underlying WS objects have an `allowHalfOpen` field, but at the moment I was not able to tweak that. And not sure if it is the cause.

Thanks !

**Comment by bantingGamer** [comment]
If you addd the **keepAlive** property. The onDisconnect will fire about 10-30 seconds after you turn on airplane mode or disconnect the wifi/internet from the device. the only problem is that it doesn't matter what value i give **keepAlive** it still takes as long as it takes. so im thinking there is a some bug with that input.

```
new SubscriptionServer({
      schema: mySchema,
      keepAlive: 1000,
      onDisconnect: (webSocket, context) => {
        console.log('>>>> DISCONNECTED WS')
      },
      execute,
      subscribe,
    }, {
      server: server,
      path: '/subscriptions',
    })
  },
```

would be nice to get some feedback from peeps that have tried this out. 
If anyone can help solve the timing issue that would be fantastic.

**Comment by sneko** [comment]
Hi,

To sum up (from what I understand):

"Keep-alive" is helping the client side making sure the connection is still up by receiving recurrent server signals (`ka`). It prevents being not aware of a shut down router (for example) that is not a proper termination triggering explicit close of both sides. (related work forf this repo https://github.com/apollographql/subscriptions-transport-ws/pull/22)

On the other side, there is the opposite "pattern" so the server can detect the connection is lost (but it could be bidirectionnal):
* The server sends a "ping" every X interval
* The client has to reply "pong" within a timeout defined otherwise the server considers the connection as lost (which help freeing memory and doing specific stuff like updating client status in the database...)

Usually the ping hexa corresponds to 9 and the pong to 10. This is implemented in some servers and clients across the WS community but I did not find anything about this for `subscriptions-transport-ws`.

Is it on the roadmap? On did someone implement that in the past? If I'm wrong tell me, maybe I misunderstood something.

Note that it's "officially" described in https://tools.ietf.org/html/rfc6455#section-5.5.2

Thank you,

cc @rricard @helfer
