### ISSUE TITLE
Is the reconnect backoff working?

### ISSUE THREAD

**Issue by pward123** [apollographql/subscriptions-transport-ws#70]
I just upgraded to 0.5.0 to get reconnect working. It seems to really hammer the browser when I kill my graphql server. It gets so bad after a couple minutes that I can't even kill the tab in Chrome.

Is the backoff delay working currently?

**Comment by NeoPhi** [comment]
It looks like a change in behavior is causing a reconnect storm to occur. @Urigo was there a use case that required adding https://github.com/apollographql/subscriptions-transport-ws/blame/master/src/client.ts#L265-L267 my understanding is that `onclose` is the only time we should attempt a reconnect. Otherwise a `onerror` fires followed by an `onclose` which we aren't guarding for.

**Comment by NeoPhi** [comment]
Looks like not having the `onerror` leads to uncaught exceptions in the tests.
