### ISSUE TITLE
SubscriptionClient.onError returning event { isTrusted: false }

### ISSUE THREAD

**Issue by LaVielle** [apollographql/subscriptions-transport-ws#744]
I'm setting up Apollo subscriptions and having auth problems.

I build the SubscriptionClient like this:
```JavaScript
const webSocketClient = new SubscriptionClient(
  AppConfig.APOLLO_WEBSOCKET_ENDPOINT,
  {
    lazy: true,
    reconnect: true,
    connectionParams: () => {
      let accessToken = ''

      // get auth token stored in Redux

      try {
        const token = store.getState().getIn(['user', 'token'])
        accessToken = token && token.get('access_token')
      } catch (e) {
        tracker.logError(`Error getting access token in webSocketClient: ${e}`)
      }

      return {
        viewer: {
          AuthorizationToken: accessToken,
        },
      }
    },
  },
  null,
  []
)

webSocketClient.onError((err) => console.log('onError', { err }))
```

The backend is somehow not handling the auth correctly so it fails and `onError` fires. The payload looks like this:
```JavaScript
Event {isTrusted: false}
```
From what I read, this is JavaScript telling me some error occurred in some third party file, but not telling me what/where for security concerns.
Is that true?
How can I get more meaningful error message from this setup?
What might be causing auth to fail with such a setup?

**Comment by kevboh** [comment]
I'm also seeing this. It appears that instead of emitting an error, the `onError` method and `.on('error', ...)` emit an internal `Event` representation. I can't find any error details within the event, and the event seems to be emitted whether or not an actual error occurs.

More generally, this repo seems abandoned. Is it? What is a viable way to use websocket connections with Apollo?
