### ISSUE TITLE
How to handle SIGTERM with this?

### ISSUE THREAD

**Issue by fabis94** [apollographql/subscriptions-transport-ws#746]
It's not clear how to make the WebSocket server stop accepting new connections, finish all pending operations and close the sockets, when SIGTERM is received. Has anyone dealt with this?

**Comment by jedwards1211** [comment]
Looks like the server does have a [`close()` method](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L197) that closes the WebSocket server.  That definitely makes it stop accepting new connections.

But, looking at the `ws` code, it [`terminates` all clients](https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L140), which I'm pretty sure means it closes them immediately instead of waiting for pending operations to finish.

So, you'd probably need to manually handle HTTP `upgrade` requests yourself so that you can stop passing them to the WebSocket server after you've received SIGTERM.  For some examples on how to handle the upgrades manually, see https://github.com/apollographql/apollo-server/pull/2314#issuecomment-593059822 and my gist linked earlier in that comment thread.

As far as waiting for pending operations to finish, I'm not 100% sure.  You might need to put some middleware between each socket and `subscriptions-transport-ws` to stop accepting new subscription requests after SIGTERM is received.

That said, it does seem like this library would be the best place to perform a managed shutdown, if an API for it could be added.
